name: Deploy Files

on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  deploy-main:
    needs: build
    name: "main branch"
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Download Built App Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Deploy
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "ssh.strato.de"
          remote-user: ${{ secrets.DEPLOY_USERNAME }}
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          remote-path: "./"
